/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialRouteImport } from './routes/testimonial'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NoticeRouteImport } from './routes/notice'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerRouteImport } from './routes/career'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceDetailsSlugRouteImport } from './routes/service-details.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TestimonialRoute = TestimonialRouteImport.update({
  id: '/testimonial',
  path: '/testimonial',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeRoute = NoticeRouteImport.update({
  id: '/notice',
  path: '/notice',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceDetailsSlugRoute = ServiceDetailsSlugRouteImport.update({
  id: '/service-details/$slug',
  path: '/service-details/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/notice': typeof NoticeRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/testimonial': typeof TestimonialRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/service-details/$slug': typeof ServiceDetailsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/notice': typeof NoticeRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/testimonial': typeof TestimonialRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/service-details/$slug': typeof ServiceDetailsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/notice': typeof NoticeRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/testimonial': typeof TestimonialRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/service-details/$slug': typeof ServiceDetailsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/blog'
    | '/career'
    | '/contact'
    | '/faq'
    | '/notice'
    | '/pricing'
    | '/services'
    | '/team'
    | '/testimonial'
    | '/blog/$slug'
    | '/service-details/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/blog'
    | '/career'
    | '/contact'
    | '/faq'
    | '/notice'
    | '/pricing'
    | '/services'
    | '/team'
    | '/testimonial'
    | '/blog/$slug'
    | '/service-details/$slug'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/blog'
    | '/career'
    | '/contact'
    | '/faq'
    | '/notice'
    | '/pricing'
    | '/services'
    | '/team'
    | '/testimonial'
    | '/blog/$slug'
    | '/service-details/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  NoticeRoute: typeof NoticeRoute
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  TestimonialRoute: typeof TestimonialRoute
  ServiceDetailsSlugRoute: typeof ServiceDetailsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonial': {
      id: '/testimonial'
      path: '/testimonial'
      fullPath: '/testimonial'
      preLoaderRoute: typeof TestimonialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notice': {
      id: '/notice'
      path: '/notice'
      fullPath: '/notice'
      preLoaderRoute: typeof NoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-details/$slug': {
      id: '/service-details/$slug'
      path: '/service-details/$slug'
      fullPath: '/service-details/$slug'
      preLoaderRoute: typeof ServiceDetailsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  NoticeRoute: NoticeRoute,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  TestimonialRoute: TestimonialRoute,
  ServiceDetailsSlugRoute: ServiceDetailsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
